# Generated by Django 5.2.1 on 2025-06-04 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_donacion_fecha_donante_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
